# rustfmt configuration for Life of Pi
# Follows Rust coding standards with some project-specific preferences

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"

# Function formatting
fn_single_line = false
where_single_line = false

# Control flow
match_block_trailing_comma = false
trailing_comma = "Vertical"

# Comments and documentation
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80

# Misc formatting
newline_style = "Unix"
remove_nested_parens = true
use_small_heuristics = "Default"