name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests weekly on Sunday at 02:00 UTC
    - cron: '0 2 * * 0'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable, beta, nightly]
        exclude:
          # Beta and nightly are redundant on macOS for our use case
          - os: macos-latest
            rust: beta
          - os: macos-latest
            rust: nightly

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.rust }}-
          ${{ runner.os }}-cargo-

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -A clippy::module_name_repetitions

    - name: Build
      run: cargo build --verbose --all-features

    - name: Run unit tests
      run: cargo test --lib --verbose
      timeout-minutes: 10

    - name: Run integration tests
      run: cargo test --test integration_tests --verbose
      timeout-minutes: 15

    - name: Run doc tests
      run: cargo test --doc --verbose
      timeout-minutes: 5

  cross-compile:
    name: Cross Compilation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: 
          - aarch64-unknown-linux-gnu  # Raspberry Pi 4/5 64-bit
          - armv7-unknown-linux-gnueabihf  # Raspberry Pi 32-bit
          - x86_64-unknown-linux-gnu   # Regular Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        targets: ${{ matrix.target }}

    - name: Install cross-compilation tools
      run: |
        cargo install cross --git https://github.com/cross-rs/cross
        # Ensure cross is in PATH
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cross-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cross-${{ matrix.target }}-
          cross-

    - name: Cross compile
      run: cross build --target ${{ matrix.target }} --release --verbose

    - name: Upload cross-compiled binaries
      uses: actions/upload-artifact@v4
      with:
        name: life_of_pi-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/life_of_pi
        retention-days: 7

  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: bench-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Run benchmarks
      run: |
        cargo bench --bench system_benchmarks -- --output-format json > benchmark_results.json 2>&1 || true
        # Ensure we have some output even if benchmarks fail
        [ -s benchmark_results.json ] || echo '[]' > benchmark_results.json

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      with:
        tool: 'criterion'
        output-file-path: benchmark_results.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: false
        comment-on-alert: true
        alert-threshold: '200%'
        fail-on-alert: false
        summary-always: true

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run security audit
      run: cargo audit

    - name: Run cargo-deny
      uses: EmbarkStudios/cargo-deny-action@v2
      with:
        log-level: warn
        command: check

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        components: llvm-tools-preview

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Generate code coverage
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: env.CODECOV_TOKEN != ''
      with:
        files: lcov.info
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release-artifacts:
    name: Build Release Artifacts
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        target: 
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - x86_64-unknown-linux-gnu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        targets: ${{ matrix.target }}

    - name: Install cross-compilation tools
      run: |
        cargo install cross --git https://github.com/cross-rs/cross
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Cross compile release
      run: cross build --target ${{ matrix.target }} --release

    - name: Create release archive
      run: |
        mkdir -p release
        cp target/${{ matrix.target }}/release/life_of_pi release/
        [ -f README.md ] && cp README.md release/ || echo "README.md not found, skipping"
        [ -f LICENSE ] && cp LICENSE release/ || echo "LICENSE not found, skipping"
        [ -f LICENSE-MIT ] && cp LICENSE-MIT release/ || echo "LICENSE-MIT not found, skipping"
        [ -f LICENSE-APACHE ] && cp LICENSE-APACHE release/ || echo "LICENSE-APACHE not found, skipping"
        cd release
        tar czf ../life_of_pi-${{ github.ref_name }}-${{ matrix.target }}.tar.gz *

    - name: Upload release assets
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.target }}
        path: life_of_pi-${{ github.ref_name }}-${{ matrix.target }}.tar.gz

  msrv:
    name: Minimum Supported Rust Version
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust 1.70 (MSRV)
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: 1.70.0

    - name: Cache cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: msrv-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Check MSRV compatibility
      run: cargo check --lib --bins

    - name: Test with MSRV (basic tests only)
      run: cargo test --lib --no-default-features
